-- 0030_industry_seed.sql — 업종 23개 + 시드 검색어 253개
--
-- ⚠ 자동 생성 파일. 손으로 고치지 말 것.
--   원본: lib/industry/taxonomy.ts · lib/industry/seeds.ts
--   재생성: node scripts/gen-industry-seed.mjs
-- 화면 라벨(TS)과 크롤 대상(DB)이 갈라지면 "메뉴에는 있는데 수집은 안 도는" 업종이 생긴다.
--
-- 한 바퀴 원가: 검색어 253개 × 커서 2페이지 = 공급사 호출 506회.
-- crawl_budget.calls_limit(기본 420)에 걸려 약 1.2일에 한 바퀴가 돈다.

insert into public.industries (id, name_ko, group_key, sort_order) values
  ('beauty', '뷰티·화장품', 'beauty_fashion', 10),
  ('skincare_clinic', '피부·성형', 'beauty_fashion', 20),
  ('fashion', '패션·의류', 'beauty_fashion', 30),
  ('accessory', '주얼리·잡화', 'beauty_fashion', 40),
  ('food', '식품·간편식', 'food_health', 50),
  ('health_supplement', '건강기능식품', 'food_health', 60),
  ('diet_fitness', '다이어트·피트니스', 'food_health', 70),
  ('dining', '외식·카페', 'food_health', 80),
  ('living', '리빙·인테리어', 'living_home', 90),
  ('household', '생활용품', 'living_home', 100),
  ('baby_kids', '유아·출산', 'living_home', 110),
  ('pet', '반려동물', 'living_home', 120),
  ('appliance', '가전·디지털기기', 'living_home', 130),
  ('medical', '병원·의료', 'service_local', 140),
  ('education', '교육·학원', 'service_local', 150),
  ('travel', '여행·숙박', 'service_local', 160),
  ('franchise', '프랜차이즈·창업', 'service_local', 170),
  ('wedding', '웨딩·행사', 'service_local', 180),
  ('it_saas', 'IT·앱·SaaS', 'digital_finance', 190),
  ('finance', '금융·보험', 'digital_finance', 200),
  ('realestate', '부동산', 'digital_finance', 210),
  ('game_content', '게임·콘텐츠', 'digital_finance', 220),
  ('etc', '기타', 'digital_finance', 999)
on conflict (id) do update
  set name_ko = excluded.name_ko,
      group_key = excluded.group_key,
      sort_order = excluded.sort_order;

insert into public.industry_keywords (industry_id, platform, keyword, origin, weight) values
  ('beauty', 'meta_ads', '기초화장품', 'seed', 200),
  ('beauty', 'meta_ads', '앰플', 'seed', 195),
  ('beauty', 'meta_ads', '선크림', 'seed', 190),
  ('beauty', 'meta_ads', '쿠션팩트', 'seed', 185),
  ('beauty', 'meta_ads', '탈모샴푸', 'seed', 180),
  ('beauty', 'meta_ads', '여드름', 'seed', 175),
  ('beauty', 'meta_ads', '모공', 'seed', 170),
  ('beauty', 'meta_ads', '미백크림', 'seed', 165),
  ('beauty', 'meta_ads', '클렌징오일', 'seed', 160),
  ('beauty', 'meta_ads', '속눈썹영양제', 'seed', 155),
  ('beauty', 'instagram', '뷰티', 'seed', 140),
  ('beauty', 'instagram', '화장품추천', 'seed', 135),
  ('beauty', 'instagram', '스킨케어', 'seed', 130),
  ('beauty', 'instagram', '피부관리', 'seed', 125),
  ('beauty', 'instagram', '메이크업', 'seed', 120),
  ('skincare_clinic', 'meta_ads', '피부과', 'seed', 200),
  ('skincare_clinic', 'meta_ads', '리프팅', 'seed', 195),
  ('skincare_clinic', 'meta_ads', '보톡스', 'seed', 190),
  ('skincare_clinic', 'meta_ads', '필러', 'seed', 185),
  ('skincare_clinic', 'meta_ads', '제모', 'seed', 180),
  ('skincare_clinic', 'meta_ads', '여드름흉터', 'seed', 175),
  ('skincare_clinic', 'meta_ads', '울쎄라', 'seed', 170),
  ('skincare_clinic', 'meta_ads', '지방분해주사', 'seed', 165),
  ('skincare_clinic', 'instagram', '피부과', 'seed', 140),
  ('skincare_clinic', 'instagram', '리프팅', 'seed', 135),
  ('skincare_clinic', 'instagram', '성형외과', 'seed', 130),
  ('skincare_clinic', 'instagram', '쁘띠성형', 'seed', 125),
  ('fashion', 'meta_ads', '여성의류', 'seed', 200),
  ('fashion', 'meta_ads', '남자코디', 'seed', 195),
  ('fashion', 'meta_ads', '원피스', 'seed', 190),
  ('fashion', 'meta_ads', '빅사이즈', 'seed', 185),
  ('fashion', 'meta_ads', '골프웨어', 'seed', 180),
  ('fashion', 'meta_ads', '언더웨어', 'seed', 175),
  ('fashion', 'meta_ads', '니트', 'seed', 170),
  ('fashion', 'meta_ads', '코트', 'seed', 165),
  ('fashion', 'instagram', '오오티디', 'seed', 140),
  ('fashion', 'instagram', '데일리룩', 'seed', 135),
  ('fashion', 'instagram', '패션스타그램', 'seed', 130),
  ('fashion', 'instagram', '코디추천', 'seed', 125),
  ('fashion', 'instagram', '쇼핑몰추천', 'seed', 120),
  ('accessory', 'meta_ads', '실버반지', 'seed', 200),
  ('accessory', 'meta_ads', '커플링', 'seed', 195),
  ('accessory', 'meta_ads', '안경테', 'seed', 190),
  ('accessory', 'meta_ads', '가방', 'seed', 185),
  ('accessory', 'meta_ads', '지갑', 'seed', 180),
  ('accessory', 'meta_ads', '시계추천', 'seed', 175),
  ('accessory', 'meta_ads', '귀걸이', 'seed', 170),
  ('accessory', 'instagram', '주얼리', 'seed', 140),
  ('accessory', 'instagram', '가방추천', 'seed', 135),
  ('accessory', 'instagram', '액세서리', 'seed', 130),
  ('food', 'meta_ads', '밀키트', 'seed', 200),
  ('food', 'meta_ads', '간편식', 'seed', 195),
  ('food', 'meta_ads', '냉동식품', 'seed', 190),
  ('food', 'meta_ads', '곱창', 'seed', 185),
  ('food', 'meta_ads', '닭가슴살', 'seed', 180),
  ('food', 'meta_ads', '선물세트', 'seed', 175),
  ('food', 'meta_ads', '반찬배달', 'seed', 170),
  ('food', 'meta_ads', '홍삼', 'seed', 165),
  ('food', 'instagram', '먹스타그램', 'seed', 140),
  ('food', 'instagram', '밀키트추천', 'seed', 135),
  ('food', 'instagram', '집밥', 'seed', 130),
  ('food', 'instagram', '간편식', 'seed', 125),
  ('health_supplement', 'meta_ads', '유산균', 'seed', 200),
  ('health_supplement', 'meta_ads', '루테인', 'seed', 195),
  ('health_supplement', 'meta_ads', '오메가3', 'seed', 190),
  ('health_supplement', 'meta_ads', '콜라겐', 'seed', 185),
  ('health_supplement', 'meta_ads', '관절영양제', 'seed', 180),
  ('health_supplement', 'meta_ads', '간건강', 'seed', 175),
  ('health_supplement', 'meta_ads', '혈당관리', 'seed', 170),
  ('health_supplement', 'meta_ads', '갱년기', 'seed', 165),
  ('health_supplement', 'instagram', '영양제추천', 'seed', 140),
  ('health_supplement', 'instagram', '건강관리', 'seed', 135),
  ('health_supplement', 'instagram', '유산균', 'seed', 130),
  ('diet_fitness', 'meta_ads', '다이어트보조제', 'seed', 200),
  ('diet_fitness', 'meta_ads', '체지방감소', 'seed', 195),
  ('diet_fitness', 'meta_ads', 'PT', 'seed', 190),
  ('diet_fitness', 'meta_ads', '홈트', 'seed', 185),
  ('diet_fitness', 'meta_ads', '요가원', 'seed', 180),
  ('diet_fitness', 'meta_ads', '필라테스', 'seed', 175),
  ('diet_fitness', 'meta_ads', '단백질쉐이크', 'seed', 170),
  ('diet_fitness', 'meta_ads', '체중감량', 'seed', 165),
  ('diet_fitness', 'instagram', '다이어트', 'seed', 140),
  ('diet_fitness', 'instagram', '헬스타그램', 'seed', 135),
  ('diet_fitness', 'instagram', '운동하는여자', 'seed', 130),
  ('diet_fitness', 'instagram', '바디프로필', 'seed', 125),
  ('diet_fitness', 'instagram', '홈트', 'seed', 120),
  ('dining', 'meta_ads', '맛집', 'seed', 200),
  ('dining', 'meta_ads', '배달', 'seed', 195),
  ('dining', 'meta_ads', '치킨', 'seed', 190),
  ('dining', 'meta_ads', '카페창업', 'seed', 185),
  ('dining', 'meta_ads', '무한리필', 'seed', 180),
  ('dining', 'meta_ads', '회식', 'seed', 175),
  ('dining', 'meta_ads', '디저트', 'seed', 170),
  ('dining', 'instagram', '맛집추천', 'seed', 140),
  ('dining', 'instagram', '카페투어', 'seed', 135),
  ('dining', 'instagram', '디저트', 'seed', 130),
  ('dining', 'instagram', '먹방', 'seed', 125),
  ('living', 'meta_ads', '인테리어', 'seed', 200),
  ('living', 'meta_ads', '소파', 'seed', 195),
  ('living', 'meta_ads', '매트리스', 'seed', 190),
  ('living', 'meta_ads', '조명', 'seed', 185),
  ('living', 'meta_ads', '커튼', 'seed', 180),
  ('living', 'meta_ads', '이사청소', 'seed', 175),
  ('living', 'meta_ads', '붙박이장', 'seed', 170),
  ('living', 'meta_ads', '리모델링', 'seed', 165),
  ('living', 'instagram', '인테리어', 'seed', 140),
  ('living', 'instagram', '집꾸미기', 'seed', 135),
  ('living', 'instagram', '홈스타일링', 'seed', 130),
  ('living', 'instagram', '자취방', 'seed', 125),
  ('household', 'meta_ads', '물티슈', 'seed', 200),
  ('household', 'meta_ads', '주방세제', 'seed', 195),
  ('household', 'meta_ads', '칫솔', 'seed', 190),
  ('household', 'meta_ads', '수건', 'seed', 185),
  ('household', 'meta_ads', '제습기', 'seed', 180),
  ('household', 'meta_ads', '베개', 'seed', 175),
  ('household', 'meta_ads', '청소기', 'seed', 170),
  ('household', 'meta_ads', '정리수납', 'seed', 165),
  ('household', 'instagram', '살림템', 'seed', 140),
  ('household', 'instagram', '생활꿀팁', 'seed', 135),
  ('household', 'instagram', '정리수납', 'seed', 130),
  ('baby_kids', 'meta_ads', '기저귀', 'seed', 200),
  ('baby_kids', 'meta_ads', '분유', 'seed', 195),
  ('baby_kids', 'meta_ads', '유모차', 'seed', 190),
  ('baby_kids', 'meta_ads', '카시트', 'seed', 185),
  ('baby_kids', 'meta_ads', '아기띠', 'seed', 180),
  ('baby_kids', 'meta_ads', '산후조리원', 'seed', 175),
  ('baby_kids', 'meta_ads', '임산부영양제', 'seed', 170),
  ('baby_kids', 'meta_ads', '유아교구', 'seed', 165),
  ('baby_kids', 'instagram', '육아스타그램', 'seed', 140),
  ('baby_kids', 'instagram', '아기용품', 'seed', 135),
  ('baby_kids', 'instagram', '신생아', 'seed', 130),
  ('baby_kids', 'instagram', '육아템', 'seed', 125),
  ('pet', 'meta_ads', '강아지사료', 'seed', 200),
  ('pet', 'meta_ads', '고양이모래', 'seed', 195),
  ('pet', 'meta_ads', '펫보험', 'seed', 190),
  ('pet', 'meta_ads', '반려견간식', 'seed', 185),
  ('pet', 'meta_ads', '동물병원', 'seed', 180),
  ('pet', 'meta_ads', '탈취제', 'seed', 175),
  ('pet', 'meta_ads', '노즈워크', 'seed', 170),
  ('pet', 'instagram', '멍스타그램', 'seed', 140),
  ('pet', 'instagram', '냥스타그램', 'seed', 135),
  ('pet', 'instagram', '반려견', 'seed', 130),
  ('pet', 'instagram', '강아지용품', 'seed', 125),
  ('appliance', 'meta_ads', '로봇청소기', 'seed', 200),
  ('appliance', 'meta_ads', '무선청소기', 'seed', 195),
  ('appliance', 'meta_ads', '에어프라이어', 'seed', 190),
  ('appliance', 'meta_ads', '노트북', 'seed', 185),
  ('appliance', 'meta_ads', '공기청정기', 'seed', 180),
  ('appliance', 'meta_ads', '안마의자', 'seed', 175),
  ('appliance', 'meta_ads', '정수기렌탈', 'seed', 170),
  ('appliance', 'meta_ads', 'TV', 'seed', 165),
  ('appliance', 'instagram', '가전추천', 'seed', 140),
  ('appliance', 'instagram', '신혼가전', 'seed', 135),
  ('appliance', 'instagram', '자취가전', 'seed', 130),
  ('medical', 'meta_ads', '한의원', 'seed', 200),
  ('medical', 'meta_ads', '치과', 'seed', 195),
  ('medical', 'meta_ads', '임플란트', 'seed', 190),
  ('medical', 'meta_ads', '교정', 'seed', 185),
  ('medical', 'meta_ads', '도수치료', 'seed', 180),
  ('medical', 'meta_ads', '탈모치료', 'seed', 175),
  ('medical', 'meta_ads', '안과', 'seed', 170),
  ('medical', 'meta_ads', '건강검진', 'seed', 165),
  ('medical', 'meta_ads', '다이어트한약', 'seed', 160),
  ('medical', 'instagram', '치과', 'seed', 140),
  ('medical', 'instagram', '한의원', 'seed', 135),
  ('medical', 'instagram', '임플란트', 'seed', 130),
  ('education', 'meta_ads', '영어회화', 'seed', 200),
  ('education', 'meta_ads', '코딩학원', 'seed', 195),
  ('education', 'meta_ads', '공무원인강', 'seed', 190),
  ('education', 'meta_ads', '자격증', 'seed', 185),
  ('education', 'meta_ads', '논술', 'seed', 180),
  ('education', 'meta_ads', '수학학원', 'seed', 175),
  ('education', 'meta_ads', '유학', 'seed', 170),
  ('education', 'meta_ads', '성인취미', 'seed', 165),
  ('education', 'instagram', '공부스타그램', 'seed', 140),
  ('education', 'instagram', '영어공부', 'seed', 135),
  ('education', 'instagram', '자격증공부', 'seed', 130),
  ('travel', 'meta_ads', '제주도여행', 'seed', 200),
  ('travel', 'meta_ads', '동남아패키지', 'seed', 195),
  ('travel', 'meta_ads', '호텔특가', 'seed', 190),
  ('travel', 'meta_ads', '풀빌라', 'seed', 185),
  ('travel', 'meta_ads', '일본자유여행', 'seed', 180),
  ('travel', 'meta_ads', '캠핑장', 'seed', 175),
  ('travel', 'meta_ads', '크루즈', 'seed', 170),
  ('travel', 'meta_ads', '렌터카', 'seed', 165),
  ('travel', 'instagram', '여행스타그램', 'seed', 140),
  ('travel', 'instagram', '국내여행', 'seed', 135),
  ('travel', 'instagram', '호캉스', 'seed', 130),
  ('travel', 'instagram', '캠핑', 'seed', 125),
  ('franchise', 'meta_ads', '창업', 'seed', 200),
  ('franchise', 'meta_ads', '무인매장', 'seed', 195),
  ('franchise', 'meta_ads', '프랜차이즈', 'seed', 190),
  ('franchise', 'meta_ads', '소자본창업', 'seed', 185),
  ('franchise', 'meta_ads', '부업', 'seed', 180),
  ('franchise', 'meta_ads', '배달전문점', 'seed', 175),
  ('franchise', 'meta_ads', '카페창업비용', 'seed', 170),
  ('franchise', 'instagram', '창업일기', 'seed', 140),
  ('franchise', 'instagram', '사장님', 'seed', 135),
  ('franchise', 'instagram', '자영업', 'seed', 130),
  ('wedding', 'meta_ads', '스드메', 'seed', 200),
  ('wedding', 'meta_ads', '웨딩홀', 'seed', 195),
  ('wedding', 'meta_ads', '청첩장', 'seed', 190),
  ('wedding', 'meta_ads', '돌잔치', 'seed', 185),
  ('wedding', 'meta_ads', '예물', 'seed', 180),
  ('wedding', 'meta_ads', '허니문', 'seed', 175),
  ('wedding', 'meta_ads', '웨딩촬영', 'seed', 170),
  ('wedding', 'meta_ads', '혼수', 'seed', 165),
  ('wedding', 'instagram', '웨딩스타그램', 'seed', 140),
  ('wedding', 'instagram', '예신', 'seed', 135),
  ('wedding', 'instagram', '웨딩드레스', 'seed', 130),
  ('wedding', 'instagram', '신혼부부', 'seed', 125),
  ('it_saas', 'meta_ads', '업무자동화', 'seed', 200),
  ('it_saas', 'meta_ads', '그룹웨어', 'seed', 195),
  ('it_saas', 'meta_ads', '쇼핑몰솔루션', 'seed', 190),
  ('it_saas', 'meta_ads', '홈페이지제작', 'seed', 185),
  ('it_saas', 'meta_ads', 'ERP', 'seed', 180),
  ('it_saas', 'meta_ads', '재고관리', 'seed', 175),
  ('it_saas', 'meta_ads', '전자계약', 'seed', 170),
  ('it_saas', 'meta_ads', 'AI챗봇', 'seed', 165),
  ('it_saas', 'instagram', '개발자', 'seed', 140),
  ('it_saas', 'instagram', '스타트업', 'seed', 135),
  ('it_saas', 'instagram', '노션', 'seed', 130),
  ('finance', 'meta_ads', '실비보험', 'seed', 200),
  ('finance', 'meta_ads', '암보험', 'seed', 195),
  ('finance', 'meta_ads', '대출', 'seed', 190),
  ('finance', 'meta_ads', '신용점수', 'seed', 185),
  ('finance', 'meta_ads', '적금', 'seed', 180),
  ('finance', 'meta_ads', '연금', 'seed', 175),
  ('finance', 'meta_ads', '주식앱', 'seed', 170),
  ('finance', 'meta_ads', '카드추천', 'seed', 165),
  ('finance', 'instagram', '재테크', 'seed', 140),
  ('finance', 'instagram', '주식투자', 'seed', 135),
  ('finance', 'instagram', '경제공부', 'seed', 130),
  ('realestate', 'meta_ads', '분양', 'seed', 200),
  ('realestate', 'meta_ads', '오피스텔', 'seed', 195),
  ('realestate', 'meta_ads', '아파트청약', 'seed', 190),
  ('realestate', 'meta_ads', '상가임대', 'seed', 185),
  ('realestate', 'meta_ads', '전세대출', 'seed', 180),
  ('realestate', 'meta_ads', '부동산투자', 'seed', 175),
  ('realestate', 'meta_ads', '지식산업센터', 'seed', 170),
  ('realestate', 'instagram', '부동산', 'seed', 140),
  ('realestate', 'instagram', '내집마련', 'seed', 135),
  ('realestate', 'instagram', '청약', 'seed', 130),
  ('game_content', 'meta_ads', '모바일게임', 'seed', 200),
  ('game_content', 'meta_ads', '웹툰', 'seed', 195),
  ('game_content', 'meta_ads', 'OTT', 'seed', 190),
  ('game_content', 'meta_ads', '방탈출', 'seed', 185),
  ('game_content', 'meta_ads', '굿즈', 'seed', 180),
  ('game_content', 'meta_ads', '웹소설', 'seed', 175),
  ('game_content', 'meta_ads', 'e북', 'seed', 170),
  ('game_content', 'instagram', '게임', 'seed', 140),
  ('game_content', 'instagram', '웹툰추천', 'seed', 135),
  ('game_content', 'instagram', '덕질', 'seed', 130)
on conflict (industry_id, platform, keyword) do nothing;

-- ────────────────────────────────────────────────────────────────
-- 노출 자격 롤업
--
-- is_visible 을 사람이 켜지 않는다. 브랜드 4곳 & 소재 40건을 동시에 넘긴 업종만
-- 자동으로 켜진다. 한쪽 조건만 보면 "브랜드 1곳이 소재 200건"인 업종이 통과해
-- 화면이 같은 브랜드로 도배된다.
--
-- industries 의 RLS SELECT 정책이 using (is_visible) 이므로, 자격 미달 업종은
-- 앱이 실수로 질의해도 애초에 행이 안 나온다 — 화면 코드의 실수와 무관하게 막힌다.
-- ────────────────────────────────────────────────────────────────
create or replace function public.rollup_industry_stats()
returns void as $$
begin
  with agg as (
    select i.id,
           count(distinct c.brand_id) filter (where c.brand_id is not null) as brands,
           count(c.id) as creatives
      from public.industries i
      left join public.creatives c
        on c.industry_ids @> array[i.id]
       and c.takedown_at is null
     group by i.id
  )
  update public.industries ind
     set brand_count    = agg.brands,
         creative_count = agg.creatives,
         is_visible     = (agg.brands >= 4 and agg.creatives >= 40),
         stats_at       = now()
    from agg
   where ind.id = agg.id;
end;
$$ language plpgsql security definer set search_path = public;

-- 허브 오픈 여부 판정용 — 앱이 자격 통과 업종 수를 세는 유일한 경로
create or replace function public.visible_industry_count()
returns int as $$
  select count(*)::int from public.industries where is_visible;
$$ language sql stable security definer set search_path = public;
