-- 0033_brand_seed.sql — 유명 브랜드 시드 107개
--
-- ⚠ 자동 생성 파일. 손으로 고치지 말 것.
--   원본: lib/industry/brand-seeds.ts
--   재생성: node scripts/gen-brand-seed.mjs
--
-- 왜 필요한가
-- ------------------------------------------------------------------
-- '기초화장품' 같은 일반 검색어로만 풀을 채우면 처음 보는 소규모 광고주가 잔뜩 뜬다.
-- 데이터는 맞지만 화면을 처음 연 사람에게는 "정체불명 광고 모음"으로 보인다.
-- 아는 이름이 깔려 있어야 "이 서비스가 진짜 데이터를 갖고 있구나"가 성립한다.
--
-- weight 300대라 일반 시드(200대)보다 항상 먼저 돈다. 플래너가 origin='brand' 를
-- 우선순위 20(팔로우 브랜드 바로 다음)으로 잡으므로 첫날 예산 대부분이 여기 쓰인다.
-- 브랜드 107개 × 커서 2페이지 = 첫 바퀴 214요청.
--
-- 의료는 개별 의원 상호를 넣지 않고 플랫폼 사업자만 넣었다 — 개별 의원은 데이터가
-- 얇고 분쟁 소지가 있다.

insert into public.industry_keywords (industry_id, platform, keyword, origin, weight) values
  ('beauty', 'meta_ads', '올리브영', 'brand', 340),
  ('beauty', 'meta_ads', '이니스프리', 'brand', 335),
  ('beauty', 'meta_ads', '메디큐브', 'brand', 330),
  ('beauty', 'meta_ads', '닥터지', 'brand', 325),
  ('beauty', 'meta_ads', '라운드랩', 'brand', 320),
  ('beauty', 'meta_ads', '아누아', 'brand', 315),
  ('beauty', 'meta_ads', '토리든', 'brand', 310),
  ('beauty', 'meta_ads', '마녀공장', 'brand', 305),
  ('skincare_clinic', 'meta_ads', '강남언니', 'brand', 340),
  ('skincare_clinic', 'meta_ads', '바비톡', 'brand', 335),
  ('skincare_clinic', 'meta_ads', '여신티켓', 'brand', 330),
  ('fashion', 'meta_ads', '무신사', 'brand', 340),
  ('fashion', 'meta_ads', '지그재그', 'brand', 335),
  ('fashion', 'meta_ads', '에이블리', 'brand', 330),
  ('fashion', 'meta_ads', '29CM', 'brand', 325),
  ('fashion', 'meta_ads', '브랜디', 'brand', 320),
  ('fashion', 'meta_ads', '널디', 'brand', 315),
  ('fashion', 'meta_ads', '커버낫', 'brand', 310),
  ('accessory', 'meta_ads', '젠틀몬스터', 'brand', 340),
  ('accessory', 'meta_ads', '로이드', 'brand', 335),
  ('accessory', 'meta_ads', '제이에스티나', 'brand', 330),
  ('accessory', 'meta_ads', '스톤헨지', 'brand', 325),
  ('food', 'meta_ads', '마켓컬리', 'brand', 340),
  ('food', 'meta_ads', '프레시지', 'brand', 335),
  ('food', 'meta_ads', '비비고', 'brand', 330),
  ('food', 'meta_ads', '풀무원', 'brand', 325),
  ('food', 'meta_ads', '오뚜기', 'brand', 320),
  ('food', 'meta_ads', '동원', 'brand', 315),
  ('food', 'meta_ads', '청정원', 'brand', 310),
  ('health_supplement', 'meta_ads', '종근당건강', 'brand', 340),
  ('health_supplement', 'meta_ads', '고려은단', 'brand', 335),
  ('health_supplement', 'meta_ads', '뉴트리원', 'brand', 330),
  ('health_supplement', 'meta_ads', '에스더포뮬러', 'brand', 325),
  ('health_supplement', 'meta_ads', '안국건강', 'brand', 320),
  ('diet_fitness', 'meta_ads', '다노', 'brand', 340),
  ('diet_fitness', 'meta_ads', '칼로바이', 'brand', 335),
  ('diet_fitness', 'meta_ads', '마이프로틴', 'brand', 330),
  ('diet_fitness', 'meta_ads', '그릭데이', 'brand', 325),
  ('dining', 'meta_ads', '배달의민족', 'brand', 340),
  ('dining', 'meta_ads', '요기요', 'brand', 335),
  ('dining', 'meta_ads', '컴포즈커피', 'brand', 330),
  ('dining', 'meta_ads', '메가커피', 'brand', 325),
  ('living', 'meta_ads', '오늘의집', 'brand', 340),
  ('living', 'meta_ads', '한샘', 'brand', 335),
  ('living', 'meta_ads', '시몬스', 'brand', 330),
  ('living', 'meta_ads', '에이스침대', 'brand', 325),
  ('living', 'meta_ads', '리바트', 'brand', 320),
  ('household', 'meta_ads', '다이소', 'brand', 340),
  ('household', 'meta_ads', '유한킴벌리', 'brand', 335),
  ('household', 'meta_ads', '애경', 'brand', 330),
  ('household', 'meta_ads', 'LG생활건강', 'brand', 325),
  ('baby_kids', 'meta_ads', '하기스', 'brand', 340),
  ('baby_kids', 'meta_ads', '마미포코', 'brand', 335),
  ('baby_kids', 'meta_ads', '코니바이에린', 'brand', 330),
  ('baby_kids', 'meta_ads', '페넬로페', 'brand', 325),
  ('pet', 'meta_ads', '펫프렌즈', 'brand', 340),
  ('pet', 'meta_ads', '로얄캐닌', 'brand', 335),
  ('pet', 'meta_ads', '하림펫푸드', 'brand', 330),
  ('pet', 'meta_ads', '어바웃펫', 'brand', 325),
  ('appliance', 'meta_ads', '삼성전자', 'brand', 340),
  ('appliance', 'meta_ads', 'LG전자', 'brand', 335),
  ('appliance', 'meta_ads', '다이슨', 'brand', 330),
  ('appliance', 'meta_ads', '코웨이', 'brand', 325),
  ('appliance', 'meta_ads', '위닉스', 'brand', 320),
  ('appliance', 'meta_ads', '쿠쿠', 'brand', 315),
  ('medical', 'meta_ads', '굿닥', 'brand', 340),
  ('medical', 'meta_ads', '똑닥', 'brand', 335),
  ('medical', 'meta_ads', '메디스트림', 'brand', 330),
  ('education', 'meta_ads', '야나두', 'brand', 340),
  ('education', 'meta_ads', '시원스쿨', 'brand', 335),
  ('education', 'meta_ads', '스픽', 'brand', 330),
  ('education', 'meta_ads', '해커스', 'brand', 325),
  ('education', 'meta_ads', '메가스터디', 'brand', 320),
  ('education', 'meta_ads', '에듀윌', 'brand', 315),
  ('education', 'meta_ads', '패스트캠퍼스', 'brand', 310),
  ('travel', 'meta_ads', '야놀자', 'brand', 340),
  ('travel', 'meta_ads', '여기어때', 'brand', 335),
  ('travel', 'meta_ads', '마이리얼트립', 'brand', 330),
  ('travel', 'meta_ads', '하나투어', 'brand', 325),
  ('travel', 'meta_ads', '트리플', 'brand', 320),
  ('travel', 'meta_ads', '아고다', 'brand', 315),
  ('franchise', 'meta_ads', '더본코리아', 'brand', 340),
  ('franchise', 'meta_ads', '프랭크버거', 'brand', 335),
  ('franchise', 'meta_ads', '매머드커피', 'brand', 330),
  ('franchise', 'meta_ads', '이디야', 'brand', 325),
  ('wedding', 'meta_ads', '아이웨딩', 'brand', 340),
  ('wedding', 'meta_ads', '웨딩북', 'brand', 335),
  ('wedding', 'meta_ads', '듀오웨드', 'brand', 330),
  ('it_saas', 'meta_ads', '카페24', 'brand', 340),
  ('it_saas', 'meta_ads', '아임웹', 'brand', 335),
  ('it_saas', 'meta_ads', '잔디', 'brand', 330),
  ('it_saas', 'meta_ads', '리멤버', 'brand', 325),
  ('it_saas', 'meta_ads', '사람인', 'brand', 320),
  ('it_saas', 'meta_ads', '플렉스', 'brand', 315),
  ('finance', 'meta_ads', '토스', 'brand', 340),
  ('finance', 'meta_ads', '카카오페이', 'brand', 335),
  ('finance', 'meta_ads', '뱅크샐러드', 'brand', 330),
  ('finance', 'meta_ads', '캐롯손해보험', 'brand', 325),
  ('finance', 'meta_ads', '삼성화재', 'brand', 320),
  ('realestate', 'meta_ads', '직방', 'brand', 340),
  ('realestate', 'meta_ads', '다방', 'brand', 335),
  ('realestate', 'meta_ads', '호갱노노', 'brand', 330),
  ('game_content', 'meta_ads', '넥슨', 'brand', 340),
  ('game_content', 'meta_ads', '넷마블', 'brand', 335),
  ('game_content', 'meta_ads', '카카오게임즈', 'brand', 330),
  ('game_content', 'meta_ads', '리디', 'brand', 325),
  ('game_content', 'meta_ads', '밀리의서재', 'brand', 320)
on conflict (industry_id, platform, keyword) do update
  set origin    = 'brand',
      weight    = excluded.weight,
      is_active = true;
